// Generated by Xata Codegen 0.29.4. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "user_details",
    columns: [
      { name: "Username", type: "string", unique: true },
      {
        name: "HashedPassword",
        type: "text",
        notNull: true,
        defaultValue: "occasions",
      },
      { name: "Email", type: "email", unique: true },
      {
        name: "SaltPassword",
        type: "text",
        notNull: true,
        defaultValue: "Appniche_Occasions",
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type UserDetails = InferredTypes["user_details"];
export type UserDetailsRecord = UserDetails & XataRecord;

export type DatabaseSchema = {
  user_details: UserDetailsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Appniche-s-workspace-uqsalv.us-east-1.xata.sh/db/Occasions",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
